sudo: required

language: cpp

compiler:
  - clang
  - gcc

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - wget

before_install:
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.2.2b/bazel_0.2.2b-linux-x86_64.deb'
  - sha256sum -c tools/bazel_0.2.2b-linux-x86_64.deb.sha256
  - chmod +x bazel_0.2.2b-linux-x86_64.deb
  - sudo dpkg -i bazel_0.2.2b-linux-x86_64.deb

script:
  - bazel test ...
